// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	ldap "github.com/go-ldap/ldap/v3"
	mock "github.com/stretchr/testify/mock"
)

// LdapConnInterface is an autogenerated mock type for the ldapConnInterface type
type LdapConnInterface struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *LdapConnInterface) Add(_a0 *ldap.AddRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.AddRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Bind provides a mock function with given fields: username, password
func (_m *LdapConnInterface) Bind(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *LdapConnInterface) Close() {
	_m.Called()
}

// Del provides a mock function with given fields: _a0
func (_m *LdapConnInterface) Del(_a0 *ldap.DelRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.DelRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Modify provides a mock function with given fields: modifyRequest
func (_m *LdapConnInterface) Modify(modifyRequest *ldap.ModifyRequest) error {
	ret := _m.Called(modifyRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.ModifyRequest) error); ok {
		r0 = rf(modifyRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: searchRequest
func (_m *LdapConnInterface) Search(searchRequest *ldap.SearchRequest) (*ldap.SearchResult, error) {
	ret := _m.Called(searchRequest)

	var r0 *ldap.SearchResult
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest) *ldap.SearchResult); ok {
		r0 = rf(searchRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SearchResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ldap.SearchRequest) error); ok {
		r1 = rf(searchRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLdapConnInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewLdapConnInterface creates a new instance of LdapConnInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLdapConnInterface(t mockConstructorTestingTNewLdapConnInterface) *LdapConnInterface {
	mock := &LdapConnInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
