// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LocalConfig is an autogenerated mock type for the LocalConfig type
type LocalConfig struct {
	mock.Mock
}

// Text provides a mock function with given fields: key
func (_m *LocalConfig) Text(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Value provides a mock function with given fields: key
func (_m *LocalConfig) Value(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Values provides a mock function with given fields: url
func (_m *LocalConfig) Values(url string) []string {
	ret := _m.Called(url)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

type mockConstructorTestingTNewLocalConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewLocalConfig creates a new instance of LocalConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLocalConfig(t mockConstructorTestingTNewLocalConfig) *LocalConfig {
	mock := &LocalConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
