// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	dbus "github.com/coreos/go-systemd/v22/dbus"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UnitManager is an autogenerated mock type for the UnitManager type
type UnitManager struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *UnitManager) Close() {
	_m.Called()
}

// DisableUnitFiles provides a mock function with given fields: files, runtime
func (_m *UnitManager) DisableUnitFiles(files []string, runtime bool) ([]dbus.DisableUnitFileChange, error) {
	ret := _m.Called(files, runtime)

	var r0 []dbus.DisableUnitFileChange
	if rf, ok := ret.Get(0).(func([]string, bool) []dbus.DisableUnitFileChange); ok {
		r0 = rf(files, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.DisableUnitFileChange)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, bool) error); ok {
		r1 = rf(files, runtime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableUnitFiles provides a mock function with given fields: files, runtime, force
func (_m *UnitManager) EnableUnitFiles(files []string, runtime bool, force bool) (bool, []dbus.EnableUnitFileChange, error) {
	ret := _m.Called(files, runtime, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]string, bool, bool) bool); ok {
		r0 = rf(files, runtime, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 []dbus.EnableUnitFileChange
	if rf, ok := ret.Get(1).(func([]string, bool, bool) []dbus.EnableUnitFileChange); ok {
		r1 = rf(files, runtime, force)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]dbus.EnableUnitFileChange)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func([]string, bool, bool) error); ok {
		r2 = rf(files, runtime, force)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetManagerProperty provides a mock function with given fields: prop
func (_m *UnitManager) GetManagerProperty(prop string) (string, error) {
	ret := _m.Called(prop)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prop)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceProperty provides a mock function with given fields: service, propertyName
func (_m *UnitManager) GetServiceProperty(service string, propertyName string) (*dbus.Property, error) {
	ret := _m.Called(service, propertyName)

	var r0 *dbus.Property
	if rf, ok := ret.Get(0).(func(string, string) *dbus.Property); ok {
		r0 = rf(service, propertyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.Property)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(service, propertyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnitProperty provides a mock function with given fields: unit, propertyName
func (_m *UnitManager) GetUnitProperty(unit string, propertyName string) (*dbus.Property, error) {
	ret := _m.Called(unit, propertyName)

	var r0 *dbus.Property
	if rf, ok := ret.Get(0).(func(string, string) *dbus.Property); ok {
		r0 = rf(unit, propertyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.Property)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(unit, propertyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnitTypeProperties provides a mock function with given fields: unit, unitType
func (_m *UnitManager) GetUnitTypeProperties(unit string, unitType string) (map[string]interface{}, error) {
	ret := _m.Called(unit, unitType)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = rf(unit, unitType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(unit, unitType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnitTypeProperty provides a mock function with given fields: unit, unitType, propertyName
func (_m *UnitManager) GetUnitTypeProperty(unit string, unitType string, propertyName string) (*dbus.Property, error) {
	ret := _m.Called(unit, unitType, propertyName)

	var r0 *dbus.Property
	if rf, ok := ret.Get(0).(func(string, string, string) *dbus.Property); ok {
		r0 = rf(unit, unitType, propertyName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.Property)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(unit, unitType, propertyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KillUnit provides a mock function with given fields: name, signal
func (_m *UnitManager) KillUnit(name string, signal int32) {
	_m.Called(name, signal)
}

// LinkUnitFiles provides a mock function with given fields: files, runtime, force
func (_m *UnitManager) LinkUnitFiles(files []string, runtime bool, force bool) ([]dbus.LinkUnitFileChange, error) {
	ret := _m.Called(files, runtime, force)

	var r0 []dbus.LinkUnitFileChange
	if rf, ok := ret.Get(0).(func([]string, bool, bool) []dbus.LinkUnitFileChange); ok {
		r0 = rf(files, runtime, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.LinkUnitFileChange)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, bool, bool) error); ok {
		r1 = rf(files, runtime, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnitFiles provides a mock function with given fields:
func (_m *UnitManager) ListUnitFiles() ([]dbus.UnitFile, error) {
	ret := _m.Called()

	var r0 []dbus.UnitFile
	if rf, ok := ret.Get(0).(func() []dbus.UnitFile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitFile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnitFilesByPatterns provides a mock function with given fields: states, patterns
func (_m *UnitManager) ListUnitFilesByPatterns(states []string, patterns []string) ([]dbus.UnitFile, error) {
	ret := _m.Called(states, patterns)

	var r0 []dbus.UnitFile
	if rf, ok := ret.Get(0).(func([]string, []string) []dbus.UnitFile); ok {
		r0 = rf(states, patterns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitFile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(states, patterns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnits provides a mock function with given fields:
func (_m *UnitManager) ListUnits() ([]dbus.UnitStatus, error) {
	ret := _m.Called()

	var r0 []dbus.UnitStatus
	if rf, ok := ret.Get(0).(func() []dbus.UnitStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnitsByNames provides a mock function with given fields: units
func (_m *UnitManager) ListUnitsByNames(units []string) ([]dbus.UnitStatus, error) {
	ret := _m.Called(units)

	var r0 []dbus.UnitStatus
	if rf, ok := ret.Get(0).(func([]string) []dbus.UnitStatus); ok {
		r0 = rf(units)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(units)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnitsByPatterns provides a mock function with given fields: states, patterns
func (_m *UnitManager) ListUnitsByPatterns(states []string, patterns []string) ([]dbus.UnitStatus, error) {
	ret := _m.Called(states, patterns)

	var r0 []dbus.UnitStatus
	if rf, ok := ret.Get(0).(func([]string, []string) []dbus.UnitStatus); ok {
		r0 = rf(states, patterns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(states, patterns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnitsFiltered provides a mock function with given fields: states
func (_m *UnitManager) ListUnitsFiltered(states []string) ([]dbus.UnitStatus, error) {
	ret := _m.Called(states)

	var r0 []dbus.UnitStatus
	if rf, ok := ret.Get(0).(func([]string) []dbus.UnitStatus); ok {
		r0 = rf(states)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnitStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MaskUnitFiles provides a mock function with given fields: files, runtime, force
func (_m *UnitManager) MaskUnitFiles(files []string, runtime bool, force bool) ([]dbus.MaskUnitFileChange, error) {
	ret := _m.Called(files, runtime, force)

	var r0 []dbus.MaskUnitFileChange
	if rf, ok := ret.Get(0).(func([]string, bool, bool) []dbus.MaskUnitFileChange); ok {
		r0 = rf(files, runtime, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.MaskUnitFileChange)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, bool, bool) error); ok {
		r1 = rf(files, runtime, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriptionSet provides a mock function with given fields:
func (_m *UnitManager) NewSubscriptionSet() *dbus.SubscriptionSet {
	ret := _m.Called()

	var r0 *dbus.SubscriptionSet
	if rf, ok := ret.Get(0).(func() *dbus.SubscriptionSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.SubscriptionSet)
		}
	}

	return r0
}

// Reload provides a mock function with given fields:
func (_m *UnitManager) Reload() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReloadOrRestartUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) ReloadOrRestartUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReloadOrTryRestartUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) ReloadOrTryRestartUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReloadUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) ReloadUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetFailedUnit provides a mock function with given fields: name
func (_m *UnitManager) ResetFailedUnit(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestartUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) RestartUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPropertiesSubscriber provides a mock function with given fields: updateCh, errCh
func (_m *UnitManager) SetPropertiesSubscriber(updateCh chan<- *dbus.PropertiesUpdate, errCh chan<- error) {
	_m.Called(updateCh, errCh)
}

// SetSubStateSubscriber provides a mock function with given fields: updateCh, errCh
func (_m *UnitManager) SetSubStateSubscriber(updateCh chan<- *dbus.SubStateUpdate, errCh chan<- error) {
	_m.Called(updateCh, errCh)
}

// SetUnitProperties provides a mock function with given fields: name, runtime, properties
func (_m *UnitManager) SetUnitProperties(name string, runtime bool, properties ...dbus.Property) error {
	_va := make([]interface{}, len(properties))
	for _i := range properties {
		_va[_i] = properties[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name, runtime)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool, ...dbus.Property) error); ok {
		r0 = rf(name, runtime, properties...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartTransientUnit provides a mock function with given fields: name, mode, properties, ch
func (_m *UnitManager) StartTransientUnit(name string, mode string, properties []dbus.Property, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, properties, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, []dbus.Property, chan<- string) int); ok {
		r0 = rf(name, mode, properties, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, []dbus.Property, chan<- string) error); ok {
		r1 = rf(name, mode, properties, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) StartUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StopUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) StopUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields:
func (_m *UnitManager) Subscribe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeUnits provides a mock function with given fields: interval
func (_m *UnitManager) SubscribeUnits(interval time.Duration) (<-chan map[string]*dbus.UnitStatus, <-chan error) {
	ret := _m.Called(interval)

	var r0 <-chan map[string]*dbus.UnitStatus
	if rf, ok := ret.Get(0).(func(time.Duration) <-chan map[string]*dbus.UnitStatus); ok {
		r0 = rf(interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan map[string]*dbus.UnitStatus)
		}
	}

	var r1 <-chan error
	if rf, ok := ret.Get(1).(func(time.Duration) <-chan error); ok {
		r1 = rf(interval)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// SubscribeUnitsCustom provides a mock function with given fields: interval, buffer, isChanged, filterUnit
func (_m *UnitManager) SubscribeUnitsCustom(interval time.Duration, buffer int, isChanged func(*dbus.UnitStatus, *dbus.UnitStatus) bool, filterUnit func(string) bool) (<-chan map[string]*dbus.UnitStatus, <-chan error) {
	ret := _m.Called(interval, buffer, isChanged, filterUnit)

	var r0 <-chan map[string]*dbus.UnitStatus
	if rf, ok := ret.Get(0).(func(time.Duration, int, func(*dbus.UnitStatus, *dbus.UnitStatus) bool, func(string) bool) <-chan map[string]*dbus.UnitStatus); ok {
		r0 = rf(interval, buffer, isChanged, filterUnit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan map[string]*dbus.UnitStatus)
		}
	}

	var r1 <-chan error
	if rf, ok := ret.Get(1).(func(time.Duration, int, func(*dbus.UnitStatus, *dbus.UnitStatus) bool, func(string) bool) <-chan error); ok {
		r1 = rf(interval, buffer, isChanged, filterUnit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// SystemState provides a mock function with given fields:
func (_m *UnitManager) SystemState() (*dbus.Property, error) {
	ret := _m.Called()

	var r0 *dbus.Property
	if rf, ok := ret.Get(0).(func() *dbus.Property); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.Property)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TryRestartUnit provides a mock function with given fields: name, mode, ch
func (_m *UnitManager) TryRestartUnit(name string, mode string, ch chan<- string) (int, error) {
	ret := _m.Called(name, mode, ch)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, chan<- string) int); ok {
		r0 = rf(name, mode, ch)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, chan<- string) error); ok {
		r1 = rf(name, mode, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnmaskUnitFiles provides a mock function with given fields: files, runtime
func (_m *UnitManager) UnmaskUnitFiles(files []string, runtime bool) ([]dbus.UnmaskUnitFileChange, error) {
	ret := _m.Called(files, runtime)

	var r0 []dbus.UnmaskUnitFileChange
	if rf, ok := ret.Get(0).(func([]string, bool) []dbus.UnmaskUnitFileChange); ok {
		r0 = rf(files, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbus.UnmaskUnitFileChange)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, bool) error); ok {
		r1 = rf(files, runtime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unsubscribe provides a mock function with given fields:
func (_m *UnitManager) Unsubscribe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
