apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-discover-exec-lib
  title: Service Discover Executor Library
  description: |
    A library for executing a desired command.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - service-discover
    - cli
    - lib
    - library
    - executor
    - exec
    - consul
    - go
    - backend
spec:
  type: library
  lifecycle: production
  owner: keyboard-crackers
