# ==========================================================================
# Golang Pre-Commit Hooks | https://github.com/tekwizely/pre-commit-golang
#
# !! ALL Hooks enabled by default - Comment out hooks you are not using
#
# Visit the project home page to learn more about the available Hooks,
# including useful arguments you might want to pass into them.
#
# NOTE: When passing options to hooks, if your options contain a reference
#       to an existing file, then you will need to use a trailing '--'
#       argument to separate the hook options from the modified-file list
#       that Pre-Commit passes into the hook.
#       For repo-based hooks, '--' is not needed.
#
# Consider adding aliases to longer-named hooks for easier CLI usage.
# ==========================================================================
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=2048 ]
      - id: mixed-line-ending
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 03770b1
    hooks:
      #
      # Go Build
      #
      - id: go-build-mod
      #
      # Go Mod Tidy
      #
      - id: go-mod-tidy
      #
      # Go Test
      #
      - id: go-test-mod
      #
      # Go Vet
      #
      # - id: go-vet-mod # Too aggressive, marks stuff that if changed will break the codebase
      #
      # Revive
      #
      - id: go-revive-mod
      #
      # GoSec
      #
      - id: go-sec-mod
      #
      # StaticCheck
      #
      - id: go-staticcheck-mod
      #
      # Formatters
      #
      - id: go-fmt
        args:
          - -w
      # Style Checkers
      #
      - id: go-critic
        args:
          - -disable=sloppyTypeAssert,caseOrder
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
        language_version: 16.0.0
      - id: markdownlint-cli2-fix
        language_version: 16.0.0
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
      - id: gitlint
