# must be unique in a given SonarQube instance
sonar.projectKey=service-discover
sonar.projectName=service-discover
sonar.exclusions=**/*_test.go,test/**
sonar.test.inclusions=**/*_test.go
sonar.go.golangci-lint.reportPaths=linter.out