// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LdapHandler is an autogenerated mock type for the LdapHandler type
type LdapHandler struct {
	mock.Mock
}

// AddService provides a mock function with given fields: server, service
func (_m *LdapHandler) AddService(server string, service string) error {
	ret := _m.Called(server, service)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(server, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckServerAvailability provides a mock function with given fields: write
func (_m *LdapHandler) CheckServerAvailability(write bool) error {
	ret := _m.Called(write)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(write)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryAllServersWithService provides a mock function with given fields: service
func (_m *LdapHandler) QueryAllServersWithService(service string) ([]string, error) {
	ret := _m.Called(service)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveService provides a mock function with given fields: server, service
func (_m *LdapHandler) RemoveService(server string, service string) error {
	ret := _m.Called(server, service)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(server, service)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
