// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	term "github.com/zextras/service-discover/pkg/term"
)

// InteractiveDependencies is an autogenerated mock type for the InteractiveDependencies type
type InteractiveDependencies struct {
	mock.Mock
}

// AddrResolver provides a mock function with given fields: n
func (_m *InteractiveDependencies) AddrResolver(n net.Interface) ([]net.Addr, error) {
	ret := _m.Called(n)

	var r0 []net.Addr
	if rf, ok := ret.Get(0).(func(net.Interface) []net.Addr); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.Interface) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupIP provides a mock function with given fields: s
func (_m *InteractiveDependencies) LookupIP(s string) ([]net.IP, error) {
	ret := _m.Called(s)

	var r0 []net.IP
	if rf, ok := ret.Get(0).(func(string) []net.IP); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetInterfaces provides a mock function with given fields:
func (_m *InteractiveDependencies) NetInterfaces() ([]net.Interface, error) {
	ret := _m.Called()

	var r0 []net.Interface
	if rf, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Term provides a mock function with given fields:
func (_m *InteractiveDependencies) Term() term.Terminal {
	ret := _m.Called()

	var r0 term.Terminal
	if rf, ok := ret.Get(0).(func() term.Terminal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(term.Terminal)
		}
	}

	return r0
}
