# Use glibc based distro since otherwise golang will bind with muslc if we use alpine!
FROM golang:1.16-buster as builder

WORKDIR /dist
COPY ./ /dist

RUN cd agent && go build

FROM ubuntu:18.04

LABEL maintainer="Davide Polonio <davide.polonio@zextras.com>"
LABEL description="service-discover CLI image to manually test the agent CLI without messing up your system"

RUN apt-get update && \
  apt-get install -y \
    ca-certificates \
    iproute2 \
    lsb-release \
    gnupg2 \
    ifupdown2 \
    net-tools \
    jq \
    less && \
  echo "deb [trusted=yes] https://repo.zextras.io/rc/ubuntu focal main" > /etc/apt/sources.list.d/zextras.list && \
  apt-get update && \
  apt-get install -y service-discover-base service-discover-agent systemd-sysv dbus sudo && \
  rm -rf /var/lib/apt/lists/* && \
  systemctl disable service-discover.service && \
  systemctl disable systemd-resolved.service && \
  useradd test -G sudo -s /bin/bash -m && \
  echo "test:test" | chpasswd && \
  echo 'LANG="en_US.UTF-8"' > /etc/default/locale

COPY --from=builder /dist/agent/agent /usr/bin/service-discover

ENTRYPOINT ["/sbin/init"]