version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile.ubuntu18.server
    hostname: mail.example.com
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - cluster

  agent:
    build:
      dockerfile: Dockerfile.ubuntu18.agent
    hostname: mail2.example.com
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - cluster

networks:
  cluster: {}