# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "zextras/service-discover-server"
    server.vm.hostname = "mail.example.com"
    # server.vm.network "private_network", type: "dhcp"
    server.vm.network "public_network"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "zextras/service-discover-agent"
    agent.vm.hostname = "mail2.example.com"
    # agent.vm.network "private_network", type: "dhcp"
    agent.vm.network "public_network"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end
