apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-discover-permissions-lib
  title: Service Discover Permissions Library
  description: |
    A library contains a permission interface which allows to change permissions to 600 and
    change ownership, only of the specific path, to 'service-discover' user and group.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - service-discover
    - cli
    - lib
    - library
    - permissions
    - consul
    - go
    - backend
spec:
  type: library
  lifecycle: production
  owner: keyboard-crackers
