---
apiVersion: v1
kind: Service
metadata:
  name: service-discover-agent
spec:
  selector:
    k8s-app: service-discover-agent
  ports:
    - protocol: TCP
      port: 8500
      name: consul-cluster
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-discover-agent
spec:
  serviceName: "service-discover-agent"
  replicas: 1
  selector:
    matchLabels:
      app: service-discover-agent
  template:
    metadata:
      labels:
        app: service-discover-agent
    spec:
      containers:
        - name: service-discover-agent
          image: registry.studiostorti.com/davide.polonio/service-discover-agent:latest
          ports:
            - containerPort: 8500
              name: consul-cluster
          volumeMounts:
            - name: service-discover-config
              mountPath: /etc/zextras/
            - name: service-discover-db
              mountPath: /var/zextras/
  volumeClaimTemplates:
    - metadata:
        name: service-discover-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: service-discover-db
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi