apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-discover-formatter-lib
  title: Service Discover Formatter Library
  description: |
    A library contains a package formatter which allows to render strings meant to be output to the
    final user.
    Currently the supported outputs are plain and JSON.
    - PlainRender() is intended to be used when the final reader will be a human
    - JsonRender() is intended to be used when the final reader will be another program.
    Keep in mind that the output of this format could very well be the input of another one.
    Once you implement the Formatter interface, you are free to use Render and pass the desired
    OutputFormat. The output will be saved on a string, so you will be able to perform additional
    manipulation before printing out the TTY,or you have the possibility to execute tests
    without any side effects.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - service-discover
    - cli
    - lib
    - library
    - formatter
    - render
    - plain
    - json
    - output
    - OutputFormat
    - PlainRender
    - JsonRender
    - consul
    - go
    - backend
spec:
  type: library
  lifecycle: production
  owner: keyboard-crackers
