// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	io "io"

	exec "bitbucket.org/zextras/service-discover/cli/lib/exec"

	mock "github.com/stretchr/testify/mock"

	net "net"

	systemd "bitbucket.org/zextras/service-discover/cli/lib/systemd"

	zimbra "bitbucket.org/zextras/service-discover/cli/lib/zimbra"
)

// BusinessDependencies is an autogenerated mock type for the BusinessDependencies type
type BusinessDependencies struct {
	mock.Mock
}

// AddrResolver provides a mock function with given fields: n
func (_m *BusinessDependencies) AddrResolver(n net.Interface) ([]net.Addr, error) {
	ret := _m.Called(n)

	var r0 []net.Addr
	if rf, ok := ret.Get(0).(func(net.Interface) []net.Addr); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.Interface) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCommand provides a mock function with given fields: name, args
func (_m *BusinessDependencies) CreateCommand(name string, args ...string) exec.Cmd {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 exec.Cmd
	if rf, ok := ret.Get(0).(func(string, ...string) exec.Cmd); ok {
		r0 = rf(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exec.Cmd)
		}
	}

	return r0
}

// GetuidSyscall provides a mock function with given fields:
func (_m *BusinessDependencies) GetuidSyscall() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LdapHandler provides a mock function with given fields: _a0
func (_m *BusinessDependencies) LdapHandler(_a0 zimbra.LocalConfig) zimbra.LdapHandler {
	ret := _m.Called(_a0)

	var r0 zimbra.LdapHandler
	if rf, ok := ret.Get(0).(func(zimbra.LocalConfig) zimbra.LdapHandler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(zimbra.LdapHandler)
		}
	}

	return r0
}

// LocalConfigLoader provides a mock function with given fields: path
func (_m *BusinessDependencies) LocalConfigLoader(path string) (zimbra.LocalConfig, error) {
	ret := _m.Called(path)

	var r0 zimbra.LocalConfig
	if rf, ok := ret.Get(0).(func(string) zimbra.LocalConfig); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(zimbra.LocalConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetInterfaces provides a mock function with given fields:
func (_m *BusinessDependencies) NetInterfaces() ([]net.Interface, error) {
	ret := _m.Called()

	var r0 []net.Interface
	if rf, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemdUnitHandler provides a mock function with given fields:
func (_m *BusinessDependencies) SystemdUnitHandler() (systemd.UnitManager, error) {
	ret := _m.Called()

	var r0 systemd.UnitManager
	if rf, ok := ret.Get(0).(func() systemd.UnitManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(systemd.UnitManager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Writer provides a mock function with given fields:
func (_m *BusinessDependencies) Writer() io.Writer {
	ret := _m.Called()

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	return r0
}
