// Code generated by mockery v2.13.0-beta.1. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	exec "bitbucket.org/zextras/service-discover/cli/lib/exec"

	mock "github.com/stretchr/testify/mock"

	net "net"

	systemd "bitbucket.org/zextras/service-discover/cli/lib/systemd"

	user "os/user"

	zimbra "bitbucket.org/zextras/service-discover/cli/lib/zimbra"
)

// BusinessDependencies is an autogenerated mock type for the BusinessDependencies type
type BusinessDependencies struct {
	mock.Mock
}

// AddrResolver provides a mock function with given fields: n
func (_m *BusinessDependencies) AddrResolver(n net.Interface) ([]net.Addr, error) {
	ret := _m.Called(n)

	var r0 []net.Addr
	if rf, ok := ret.Get(0).(func(net.Interface) []net.Addr); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.Interface) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Chmod provides a mock function with given fields: path, mode
func (_m *BusinessDependencies) Chmod(path string, mode fs.FileMode) error {
	ret := _m.Called(path, mode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Chown provides a mock function with given fields: path, userUid, groupUid
func (_m *BusinessDependencies) Chown(path string, userUid int, groupUid int) error {
	ret := _m.Called(path, userUid, groupUid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = rf(path, userUid, groupUid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCommand provides a mock function with given fields: name, args
func (_m *BusinessDependencies) CreateCommand(name string, args ...string) exec.Cmd {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 exec.Cmd
	if rf, ok := ret.Get(0).(func(string, ...string) exec.Cmd); ok {
		r0 = rf(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exec.Cmd)
		}
	}

	return r0
}

// GetuidSyscall provides a mock function with given fields:
func (_m *BusinessDependencies) GetuidSyscall() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// LdapHandler provides a mock function with given fields: _a0
func (_m *BusinessDependencies) LdapHandler(_a0 zimbra.LocalConfig) zimbra.LdapHandler {
	ret := _m.Called(_a0)

	var r0 zimbra.LdapHandler
	if rf, ok := ret.Get(0).(func(zimbra.LocalConfig) zimbra.LdapHandler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(zimbra.LdapHandler)
		}
	}

	return r0
}

// LocalConfigLoader provides a mock function with given fields: path
func (_m *BusinessDependencies) LocalConfigLoader(path string) (zimbra.LocalConfig, error) {
	ret := _m.Called(path)

	var r0 zimbra.LocalConfig
	if rf, ok := ret.Get(0).(func(string) zimbra.LocalConfig); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(zimbra.LocalConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupGroup provides a mock function with given fields: name
func (_m *BusinessDependencies) LookupGroup(name string) (*user.Group, error) {
	ret := _m.Called(name)

	var r0 *user.Group
	if rf, ok := ret.Get(0).(func(string) *user.Group); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupIP provides a mock function with given fields: s
func (_m *BusinessDependencies) LookupIP(s string) ([]net.IP, error) {
	ret := _m.Called(s)

	var r0 []net.IP
	if rf, ok := ret.Get(0).(func(string) []net.IP); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupUser provides a mock function with given fields: name
func (_m *BusinessDependencies) LookupUser(name string) (*user.User, error) {
	ret := _m.Called(name)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetInterfaces provides a mock function with given fields:
func (_m *BusinessDependencies) NetInterfaces() ([]net.Interface, error) {
	ret := _m.Called()

	var r0 []net.Interface
	if rf, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SystemdUnitHandler provides a mock function with given fields:
func (_m *BusinessDependencies) SystemdUnitHandler() (systemd.UnitManager, error) {
	ret := _m.Called()

	var r0 systemd.UnitManager
	if rf, ok := ret.Get(0).(func() systemd.UnitManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(systemd.UnitManager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type newBusinessDependenciesT interface {
	mock.TestingT
	Cleanup(func())
}

// newBusinessDependencies creates a new instance of BusinessDependencies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newBusinessDependencies(t newBusinessDependenciesT) *BusinessDependencies {
	mock := &BusinessDependencies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
