// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/consul/api"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// ACL provides a mock function with given fields:
func (_m *Client) ACL() *api.ACL {
	ret := _m.Called()

	var r0 *api.ACL
	if rf, ok := ret.Get(0).(func() *api.ACL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ACL)
		}
	}

	return r0
}

// Agent provides a mock function with given fields:
func (_m *Client) Agent() *api.Agent {
	ret := _m.Called()

	var r0 *api.Agent
	if rf, ok := ret.Get(0).(func() *api.Agent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Agent)
		}
	}

	return r0
}

// Catalog provides a mock function with given fields:
func (_m *Client) Catalog() *api.Catalog {
	ret := _m.Called()

	var r0 *api.Catalog
	if rf, ok := ret.Get(0).(func() *api.Catalog); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Catalog)
		}
	}

	return r0
}

// ConfigEntries provides a mock function with given fields:
func (_m *Client) ConfigEntries() *api.ConfigEntries {
	ret := _m.Called()

	var r0 *api.ConfigEntries
	if rf, ok := ret.Get(0).(func() *api.ConfigEntries); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ConfigEntries)
		}
	}

	return r0
}

// Connect provides a mock function with given fields:
func (_m *Client) Connect() *api.Connect {
	ret := _m.Called()

	var r0 *api.Connect
	if rf, ok := ret.Get(0).(func() *api.Connect); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Connect)
		}
	}

	return r0
}

// Coordinate provides a mock function with given fields:
func (_m *Client) Coordinate() *api.Coordinate {
	ret := _m.Called()

	var r0 *api.Coordinate
	if rf, ok := ret.Get(0).(func() *api.Coordinate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Coordinate)
		}
	}

	return r0
}

// Debug provides a mock function with given fields:
func (_m *Client) Debug() *api.Debug {
	ret := _m.Called()

	var r0 *api.Debug
	if rf, ok := ret.Get(0).(func() *api.Debug); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Debug)
		}
	}

	return r0
}

// DiscoveryChain provides a mock function with given fields:
func (_m *Client) DiscoveryChain() *api.DiscoveryChain {
	ret := _m.Called()

	var r0 *api.DiscoveryChain
	if rf, ok := ret.Get(0).(func() *api.DiscoveryChain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.DiscoveryChain)
		}
	}

	return r0
}

// Event provides a mock function with given fields:
func (_m *Client) Event() *api.Event {
	ret := _m.Called()

	var r0 *api.Event
	if rf, ok := ret.Get(0).(func() *api.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Event)
		}
	}

	return r0
}

// Health provides a mock function with given fields:
func (_m *Client) Health() *api.Health {
	ret := _m.Called()

	var r0 *api.Health
	if rf, ok := ret.Get(0).(func() *api.Health); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Health)
		}
	}

	return r0
}

// KV provides a mock function with given fields:
func (_m *Client) KV() *api.KV {
	ret := _m.Called()

	var r0 *api.KV
	if rf, ok := ret.Get(0).(func() *api.KV); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KV)
		}
	}

	return r0
}

// LockKey provides a mock function with given fields: key
func (_m *Client) LockKey(key string) (*api.Lock, error) {
	ret := _m.Called(key)

	var r0 *api.Lock
	if rf, ok := ret.Get(0).(func(string) *api.Lock); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Lock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockOpts provides a mock function with given fields: opts
func (_m *Client) LockOpts(opts *api.LockOptions) (*api.Lock, error) {
	ret := _m.Called(opts)

	var r0 *api.Lock
	if rf, ok := ret.Get(0).(func(*api.LockOptions) *api.Lock); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Lock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.LockOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Namespaces provides a mock function with given fields:
func (_m *Client) Namespaces() *api.Namespaces {
	ret := _m.Called()

	var r0 *api.Namespaces
	if rf, ok := ret.Get(0).(func() *api.Namespaces); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Namespaces)
		}
	}

	return r0
}

// Operator provides a mock function with given fields:
func (_m *Client) Operator() *api.Operator {
	ret := _m.Called()

	var r0 *api.Operator
	if rf, ok := ret.Get(0).(func() *api.Operator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Operator)
		}
	}

	return r0
}

// PreparedQuery provides a mock function with given fields:
func (_m *Client) PreparedQuery() *api.PreparedQuery {
	ret := _m.Called()

	var r0 *api.PreparedQuery
	if rf, ok := ret.Get(0).(func() *api.PreparedQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PreparedQuery)
		}
	}

	return r0
}

// Raw provides a mock function with given fields:
func (_m *Client) Raw() *api.Raw {
	ret := _m.Called()

	var r0 *api.Raw
	if rf, ok := ret.Get(0).(func() *api.Raw); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Raw)
		}
	}

	return r0
}

// SemaphoreOpts provides a mock function with given fields: opts
func (_m *Client) SemaphoreOpts(opts *api.SemaphoreOptions) (*api.Semaphore, error) {
	ret := _m.Called(opts)

	var r0 *api.Semaphore
	if rf, ok := ret.Get(0).(func(*api.SemaphoreOptions) *api.Semaphore); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Semaphore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.SemaphoreOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SemaphorePrefix provides a mock function with given fields: prefix, limit
func (_m *Client) SemaphorePrefix(prefix string, limit int) (*api.Semaphore, error) {
	ret := _m.Called(prefix, limit)

	var r0 *api.Semaphore
	if rf, ok := ret.Get(0).(func(string, int) *api.Semaphore); ok {
		r0 = rf(prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Semaphore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(prefix, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Session provides a mock function with given fields:
func (_m *Client) Session() *api.Session {
	ret := _m.Called()

	var r0 *api.Session
	if rf, ok := ret.Get(0).(func() *api.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Session)
		}
	}

	return r0
}

// Snapshot provides a mock function with given fields:
func (_m *Client) Snapshot() *api.Snapshot {
	ret := _m.Called()

	var r0 *api.Snapshot
	if rf, ok := ret.Get(0).(func() *api.Snapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Snapshot)
		}
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *Client) Status() *api.Status {
	ret := _m.Called()

	var r0 *api.Status
	if rf, ok := ret.Get(0).(func() *api.Status); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Status)
		}
	}

	return r0
}

// Txn provides a mock function with given fields:
func (_m *Client) Txn() *api.Txn {
	ret := _m.Called()

	var r0 *api.Txn
	if rf, ok := ret.Get(0).(func() *api.Txn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Txn)
		}
	}

	return r0
}
