// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	io "io"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// InteractiveDependencies is an autogenerated mock type for the InteractiveDependencies type
type InteractiveDependencies struct {
	mock.Mock
}

// AddrResolver provides a mock function with given fields: n
func (_m *InteractiveDependencies) AddrResolver(n net.Interface) ([]net.Addr, error) {
	ret := _m.Called(n)

	var r0 []net.Addr
	if rf, ok := ret.Get(0).(func(net.Interface) []net.Addr); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(net.Interface) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetInterfaces provides a mock function with given fields:
func (_m *InteractiveDependencies) NetInterfaces() ([]net.Interface, error) {
	ret := _m.Called()

	var r0 []net.Interface
	if rf, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reader provides a mock function with given fields:
func (_m *InteractiveDependencies) Reader() io.Reader {
	ret := _m.Called()

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	return r0
}

// Writer provides a mock function with given fields:
func (_m *InteractiveDependencies) Writer() io.Writer {
	ret := _m.Called()

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	return r0
}
